FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git unzip zip libonig-dev libzip-dev libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql mbstring zip gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Set application key (optional, but recommended)
RUN php artisan key:generate

# Run migrations AND seeders here
RUN php artisan migrate --force --seed

EXPOSE 9000

CMD ["php-fpm"]
